USE SUCOS;

SELECT * FROM TABELA_DE_VENDEDORES WHERE PERCENTUAL_COMISSAO > 0.10;

SELECT * FROM TABELA_DE_VENDEDORES;

#USANDO O WHERE PARA FILTRAR
SELECT * FROM TBPRODUTO WHERE PRODUTO = '1040107';

SELECT * FROM tbcliente WHERE CIDADE ='RIO DE JANEIRO';

SELECT * FROM TBPRODUTO WHERE SABOR = 'LIMÃO';

UPDATE tbproduto SET SABOR = 'CÍTRICOS' WHERE SABOR = 'LIMÃO';

SELECT * FROM TBPRODUTO WHERE SABOR = 'CÍTRICOS';

SELECT * FROM TBCLIENTE WHERE IDADE >22;

SELECT * FROM TBCLIENTE WHERE IDADE < 22;

SELECT * FROM TBCLIENTE WHERE IDADE <=22;

SELECT * FROM TBCLIENTE WHERE IDADE != 22;

SELECT * FROM TBCLIENTE WHERE NOME > 'Fernando Cavalcante';

SELECT * FROM TBPRODUTO WHERE PRECO_LISTA > 16.008;

SELECT * FROM TBPRODUTO WHERE PRECO_LISTA between 16.007 AND 16.009;