
use sucos;

SELECT * FROM TBCLIENTE;

ALTER TABLE TBCLIENTE ADD PRIMARY KEY(CPF);

ALTER TABLE TBCLIENTE ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO TBCLIENTE (
CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE,ESTADO,CEP,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA,DATA_NASCIMENTO) 
VALUES ('00388934505','João da Silva', 'Rua projetada A número 10',' ','Vila Roman', 'CARATINGA','Amazonas','2222222',30,'M','10000.00',2000,0,'1989-10-05');
 
ALTER TABLE tabela_de_vendedores ADD COLUMN (DATA_ADMISSÃO DATE);

ALTER TABLE tabela_de_vendedores ADD COLUMN (DE_FERIAS BIT);

SELECT * FROM tabela_de_vendedores;

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSÃO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00237','Roberta Martins','2017-03-18',0.11,1);

INSERT INTO TABELA_DE_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSÃO, PERCENTUAL_COMISSAO, DE_FERIAS)
VALUES
('00238','Pericles Alves','2016-08-21',0.11,0);

ALTER TABLE tabela_de_vendedores ADD primary key(MATRICULA);

UPDATE tabela_de_vendedores SET DATA_ADMISSÃO = '2013-09-17'
where MATRICULA = '00236';

UPDATE tabela_de_vendedores SET DE_FERIAS = 0
where MATRICULA = '00236';

